# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/api/register/league
Content-Type: application/json

{
  "leagueName": "czampionsLeague",
  "clientShortcut": "FootBallData",
  "config": {
    "leagueId": 2001
  }
}

###

POST https://ebet2-api.herokuapp.com/api/register/league
Content-Type: application/json

{
  "leagueName": "czampionsLeague",
  "clientShortcut": "FootBallData",
  "config": {
    "leagueId": 2001
  }
}

###

GET http://api.football-data.org/v2/competitions/2001/matches
X-Auth-Token: 192c1479cf52415cbbbbca218532ccfe

###

GET http://api.football-data.org/v2/competitions/2001/matches
X-Auth-Token: 192c1479cf52415cbbbbca218532ccfe

###

GET http://localhost:8080/api/leagues

###

POST https://ebet2-api.herokuapp.com/api/user/register
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

POST https://ebet2-api.herokuapp.com/api/bet
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiNWRkNWYxMGUtMjRmYi00N2RhLWJlMTItMTViMzkzNThmYmVkIn0.48Uuq1CUAMBTXP5mhOtecsr9QtyiCw5EWx-vZmPyidU

{
  "betTyp": "DRAW",
  "matchUUID": "5c75cae3-6551-47be-b336-9d410660bb4e"
}

###

GET https://ebet2-api.herokuapp.com/api/league/20c86b5a-7032-4290-911f-8e761c04b54f/matches

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username": "asd",
  "password": "asd"
}

###
